package net.unbeta.content.client.corruption;

import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;
import net.minecraft.client.render.entity.ChickenEntityRenderer;
import net.minecraft.client.render.entity.CowEntityRenderer;
import net.minecraft.client.render.entity.EntityRendererFactory;
import net.minecraft.client.render.entity.PigEntityRenderer;
import net.minecraft.client.render.entity.SheepEntityRenderer;
import net.minecraft.entity.passive.ChickenEntity;
import net.minecraft.entity.passive.CowEntity;
import net.minecraft.entity.passive.PigEntity;
import net.minecraft.entity.passive.SheepEntity;
import net.minecraft.util.Identifier;
import net.unbeta.content.corruption.CorruptionRegistry;

/**
 * Vanilla renderers and models, pointed at the tinted textures generated by
 * tools/tint_corrupted.py. No custom rendering code - swap the textures for real art later.
 */
public final class CorruptionRenderers {

    private CorruptionRenderers() {}

    private static Identifier tex(String name) {
        return new Identifier("unbeta-content", "textures/entity/corruption/" + name + ".png");
    }

    public static void register() {
        EntityRendererRegistry.register(CorruptionRegistry.ZOMBIE_COW, Cow::new);
        EntityRendererRegistry.register(CorruptionRegistry.ZOMBIE_PIG, Pig::new);
        EntityRendererRegistry.register(CorruptionRegistry.ZOMBIE_SHEEP, Sheep::new);
        EntityRendererRegistry.register(CorruptionRegistry.ZOMBIE_CHICKEN, Chicken::new);
        // Looks like any zombie - the player recognises it only by their own gear.
        EntityRendererRegistry.register(CorruptionRegistry.REVENANT,
                net.minecraft.client.render.entity.ZombieEntityRenderer::new);
    }

    public static class Cow extends CowEntityRenderer {
        private static final Identifier TEXTURE = tex("zombie_cow");
        public Cow(EntityRendererFactory.Context ctx) { super(ctx); }
        @Override public Identifier getTexture(CowEntity e) { return TEXTURE; }
    }

    public static class Pig extends PigEntityRenderer {
        private static final Identifier TEXTURE = tex("zombie_pig");
        public Pig(EntityRendererFactory.Context ctx) { super(ctx); }
        @Override public Identifier getTexture(PigEntity e) { return TEXTURE; }
    }

    public static class Sheep extends SheepEntityRenderer {
        private static final Identifier TEXTURE = tex("zombie_sheep");
        public Sheep(EntityRendererFactory.Context ctx) { super(ctx); }
        @Override public Identifier getTexture(SheepEntity e) { return TEXTURE; }
    }

    public static class Chicken extends ChickenEntityRenderer {
        private static final Identifier TEXTURE = tex("zombie_chicken");
        public Chicken(EntityRendererFactory.Context ctx) { super(ctx); }
        @Override public Identifier getTexture(ChickenEntity e) { return TEXTURE; }
    }
}
